global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'discord_bot'
    scrape_interval: 60s
    static_configs:
      - targets: ['insightful-abundance-production.up.railway.app:8000']
    scheme: https
    metrics_path: /metrics
