global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'discord_bot'
    scrape_interval: 60s
    static_configs:
      - targets: ['insightful-abundance-production.up.railway.app']
    scheme: https
    metrics_path: /metrics
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
      
remote_write:
  - url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
    basic_auth:
     username: 2222265
     password: glc_eyJvIjoiMTMyODI1OSIsIm4iOiJzdGFjay0xMTQ5MDExLWFsbG95LXByb21ldGhldXNfY29ubmVjdCIsImsiOiJscnMxMWg5cWE5MjAxM2JRMkV0T0V2OUEiLCJtIjp7InIiOiJwcm9kLXVzLWVhc3QtMCJ9fQ==
      
